### PR TITLE
Grammar setnames fix

### LINKED ISSUE #301: Fix grammar set name/element name errors
Some element and set names are inconsistent due to spaces and underscores.

### PR DESCRIPTION
**Pull request by JakeWags**
### Does this PR close any open issues?
Closes #301
Depends #302

### Give a longer description of what this PR addresses and why it's needed
Previously, there was a strange discrepancy between the downloaded json data setnames and the alt-text generated setnames. This was due to the fact that the alt-text config generation function was not adjusting the element name field prior to export.

By adding this to the alt text, the output seems to be as expected.

Tested with Simpsons and Movie dataset.

### Provide pictures/videos of the behavior before and after these changes (optional)
@elizaan 
Please confirm that this is correct:
```UpSet Introduction
 This is an UpSet plot that visualizes set intersection. To learn about UpSet plots, visit https://upset.app.
 Dataset Properties

The dataset contains 6 sets, and 44 elements, of which 6 are shown in the plot.
Set Properties

The largest set is Male with 18 elements, followed by School with 6, Duff Fan with 6, Evil with 6, Power Plant with 5, and Blue Hair with 3.
Intersection Properties

The plot is sorted by size. There are 12 non-empty intersections, all of which are shown in the plot. The largest 5 intersections are School, and Male (3), the empty intersection (3), Just Male (3), Duff Fan, Male, and Power Plant (3), and Evil, and Male (2).
Statistical Information

The average intersection size is 2, and the median is 2. The 90th percentile is 3, and the 10th percentile is 1. The largest set, Male, is present in 75.0% of all non-empty intersections. The smallest set, Blue Hair, is present in 16.7% of all non-empty intersections.
```

image

### Are there any additional TODOs before this PR is ready to go?

TODOs:
- [X] Update playwright tests
- [X] Fix issue with element names for sets with spaces in the name
- [x] Update delimiter to `~&~`

### CODE REVIEW

File: packages/upset/src/utils/exports.ts [hunk 1]
```diff
@@ -58,45 +47,54 @@ const downloadJSON = (filename: string, json: string): void => {
...
-    const splitElName = r['elementName'].split(' ');
+    const splitElName = r['elementName'].split('~&~');
+
+    let elName = splitElName.join(', ');
 
     if (splitElName.length > 1) {
       const lastWord = splitElName.pop();
-      const elName = splitElName.join(', ');
-      r['elementName'] = `${elName}, and ${lastWord}`;
+      // elName = `${elName}, and ${lastWord}`;
```
Comment (JackWilb) [inline packages/upset/src/utils/exports.ts:60]:
```suggestion
```

File: packages/upset/src/utils/exports.ts [hunk 2]
```diff
@@ -58,45 +47,54 @@ const downloadJSON = (filename: string, json: string): void => {
...
+      elName = `${splitElName.join(', ')}, and ${lastWord}`;
+    } else if (r.type === 'Aggregate') {
+      const r2 = r as Aggregate;
+      if (r2.aggregateBy === 'Overlaps') {
+        elName = elName.split(' - ').join(' & '); // overlaps look like "Adventure - Action", so replace the hyphen with " & "
```
Comment (JackWilb) [inline packages/upset/src/utils/exports.ts:65]: Is this ` - ` coming from somewhere else?

**Review by JackWilb — APPROVED** [review]

File: e2e-tests/alttext.spec.ts [hunk 3]
```diff
@@ -113,13 +113,13 @@ test('Alt Text', async ({ page }) => {
   };
   await expect(intersectionProperties.heading).toBeVisible();
   await expect(intersectionProperties.content).toBeVisible();
-  await expect(intersectionProperties.content).toHaveText('The plot is sorted by size. There are 12 non-empty intersections, all of which are shown in the plot. The largest 5 intersections are School Male (3), the empty intersection (3), Just Male (3), Duff_Fan Male Power_Plant (3), and Evil Male (2).');
+  await expect(intersectionProperties.content).toHaveText('The plot is sorted by size. There are 12 non-empty intersections, all of which are shown in the plot. The largest 5 intersections are School, and Male (3), Just Unincluded (3), Just Male (3), Duff Fan, Male, and Power Plant (3), and Evil, and Male (2).');
```
Comment (elizaan) [inline e2e-tests/alttext.spec.ts:116]: Just Unincluded was named Unincluded before. I changed the name 'Unincluded' to 'the empty intersection' while doing alt-txt generation. If you plan to keep 'Just Unincluded' let me know, and I will change my alt-txt code.
