### PR TITLE
Bugfix: Calculate plot height correctly when aggregating by sets/overlaps

### LINKED ISSUE #522: Plot not scrolling when aggregates exceed height
Try aggregate by overlaps: when the number of aggregate rows drastically exceeds the normal row count, scrolling doesn't work.

### PR DESCRIPTION
**Pull request by NateLanza**
### Does this PR close any open issues?
Closes #522 

### Give a longer description of what this PR addresses and why it's needed
Previously, aggregating by sets/overlaps caused the rows to overflow off the bottom of the page. This updates the plot height calculation to fix that.

### Have you added or updated relevant tests?
- [ ] Yes
- [x] No changes are needed

### Have you added or updated relevant documentation?
- [ ] Yes
- [x] No changes are needed

### CODE REVIEW

File: packages/upset/src/components/Rows/MatrixRows.tsx [hunk 1]
```diff
@@ -86,49 +87,36 @@ export const MatrixRows: FC<Props> = ({ rows }) => {
...
     if (queryBySetsInterface) {
-      transformShift += dimensions.setQuery.height + dimensions.setQuery.spacer;
+      return dimensions.setQuery.height + dimensions.setQuery.spacer;
     }
     if (isPopulatedSetQuery(setQuery)) {
-      transformShift += dimensions.body.rowHeight * 2;
+      return dimensions.body.rowHeight * 2;
     }
+    return 0;
+  }, [queryBySetsInterface, dimensions, setQuery]);
```
Comment (JakeWags) [inline packages/upset/src/components/Rows/MatrixRows.tsx:98]: Add docstring

**Review by JakeWags — APPROVED** [review]
Overall looks good 👍
