### PR TITLE
fix: 🐛 attribute NaN errors when loading encoded data

### LINKED ISSUE #237: one-hot encoded data isn't properly loading attributes
image

### PR DESCRIPTION
**Pull request by JakeWags**
### Does this PR close any open issues?
Closes #237

### Give a longer description of what this PR addresses and why it's needed
Updates the attribute loading to account for any `NaN` values

### Provide pictures/videos of the behavior before and after these changes (optional)
Proper behavior:
image

### Are there any additional TODOs before this PR is ready to go?

TODOs:
- [ ] ...

### CODE REVIEW

File: packages/app/src/utils/oneHotEncoding.ts [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+    if (empty) {
+        return encodedData;
+    }
+
+    // get the unique names of every new column to be added. 
+    //    ex: group1_a, group1_b, group2_a, group2_b, group3_c, ....
+    encodeList.forEach((s) => Object.entries(data.items).forEach(([id, row]) => {
+        let names = `${row[s]}`.split(',');
+        names = names.filter((n) => n !== "")
+        newColNames.push(...names.map((val) => `${s}_${val}`))
```
Comment (JackWilb) [inline packages/app/src/utils/oneHotEncoding.ts:17]: A little clean up to make this easier to follow
```suggestion
        const names = `${row[s]}`
          .split(',');
          .filter((n) => n !== "")
          .map((val) => `${s}_${val}`);
        newColNames.push(...names)
```

**Review by JackWilb — CHANGES_REQUESTED** [review]
I'm seeing some 0 values in the rows with missing values. I think we'd rather just ignore those rows, instead of adding a 0 value in

**Review by JackWilb — APPROVED** [review]
