### PR TITLE
Size scaling fixes

### LINKED ISSUE #486: Allow smaller advanced scale
The advanced scale doesn't go down all the way; this should go to a minimum value of 5 (or 5%) or so.

### LINKED ISSUE #497: set query does not update size scale
When adding a set query, the size scale is not updated accordingly

### PR DESCRIPTION
**Pull request by JakeWags**
### Does this PR close any open issues?
Closes #497 
Closes #486 

### Give a longer description of what this PR addresses and why it's needed
This PR addresses the size bar scaling for the set query rows as well as the minimum size scale.
Previously, the advanced scale minimum was 10% of the total items, which was not necessarily useful. This is especially noticeable when there are no subsets that are near the max size. See previous behavior gif below.

Now, the size scale minimum is set to EITHER 0.05% of the total items (with a minimum of 1) or 5, whichever is smaller. This means that for a small dataset (Simpsons), the minimum is 1, whereas for a large dataset (movies), the minimum is 5. For movies, the 0.05% value is something like 16, so for smaller subsets, this value is simply too large.

### Provide pictures/videos of the behavior before and after these changes (optional)
BEFORE:
upset-sizescale-prev

movies - 
upset-sizescale-prev-movies

AFTER:
upset-sizescale-after

movies - 
upset-sizescale-after-movies

### Have you added or updated relevant tests?
- [ ] Yes
- [X] No changes are needed

### Have you added or updated relevant documentation?
- [X] Yes
- [ ] No changes are needed

### Are there any additional TODOs before this PR is ready to go?

TODOs:
- None

### CODE REVIEW

**Comment by NateLanza** [comment]
I think you need to list "Closes" on separate lines; GH appears to have only picked up one issue to close

**Comment by NateLanza** [comment]
I'm noticing that a few Movies intersections don't show the white slashes denoting too large a size scale when the scale is set to 5
image

File: packages/upset/src/atoms/setQuerySizeSelector.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import { selector } from 'recoil';
+import { flattenedRowsSelector } from './renderRowsAtom';
+
```
Comment (NateLanza) [inline packages/upset/src/atoms/setQuerySizeSelector.ts:3]: Add docstring

**Review by NateLanza — CHANGES_REQUESTED** [review]
Biggest issue is functionality; see prior comment
