### PR TITLE
Plot display fixes

### LINKED ISSUE #499: hover state with query by sets is lingering
When creating a new query, the hover state can sometimes linger. This should be cleared upon adding or removing the query

### LINKED ISSUE #500: Attribute scale has a white background on text that shows on small values
Image

### PR DESCRIPTION
**Pull request by NateLanza**
### Does this PR close any open issues?
Closes #499 
Closes #500

### Give a longer description of what this PR addresses and why it's needed
- Fixes a bug where matrix column highlights would persist after opening or closing the set query interface
- Maintains the selected row when the set query is cleared
- Removes a weird white `<text>` element which was causing visual bugs from the attribute axis labels

### Have you added or updated relevant tests?
- [ ] Yes
- [x] No changes are needed

### CODE REVIEW

File: packages/upset/src/components/custom/QueryBySet/QueryBySetInterface.tsx [hunk 1]
```diff
@@ -147,24 +154,27 @@ export const QueryBySetInterface = () => {
...
+  const addQuery = useCallback(() => {
     const query = {
       name: queryName,
       query: membership,
     };
 
     actions.addSetQuery(query, queryResultString);
+    // We need to clear the current selection in case the selected row disappears after query
+    if (currentIntersection !== null) actions.setSelected(null);
+    setColumnSelect([]); // Column select doesn't clear itself for some reason
```
Comment (JakeWags) [inline packages/upset/src/components/custom/QueryBySet/QueryBySetInterface.tsx:177]: I think that this should occur before the query action. This would make more sense in the provenance history, as currently the "deselect intersection" node has no delta with the set query node.

**Review by JakeWags — CHANGES_REQUESTED** [review]
Overall looks good, but I think we should invert the order of actions when adding a query and removing selections.
