### PR TITLE
458 simplify selection

### LINKED ISSUE #383: Bookmark colors are not always consistent
Since bookmark colors are done by order, not assigned to bookmarks, they can change when items are removed from the list. This should be fixed.

For the same reason, element selections change color when selected.

firefox_zLKgNAqKfR

_Originally posted by @JakeWags in https://github.com/visdesignlab/upset2/issues/370#issuecomment-2291614260_

### LINKED ISSUE #458: Simplify Selections / Filters
I want to get out of selection logic hell, so here's my proposal to simplify selections: 

1. Element Visualizations always show all elements. We never filter anything out, not even for intersection selections. This works fine for scatterplots; might not work so well for KDEs, at least not with using default computations. We should probably replace KDEs in the element views with good old histograms. 
2. Element visualizations, always render bookmarked selections plus the active selection in color. Not selected elements get slightly transparent. 
3. Brushing a chart creates a new selection. Modifying the brush modifies the selection (does not create a new one)
4. Brushing in a second chart creates a new selection based on ALL data; there is no AND logic. 
5. In the upset bars things remain as they are now: the active selection is shown, other selections have the little triangles.

### LINKED ISSUE #461: Clicking an intersections when an attribute selection is active is broken
In the following state, I made an attribute selection. Bookmarked it, then bookmarked an intersection bar (the green one): 

Image

This also happens just with selection, not only with bookmark. 

These actions create a selection and bookmark it (when chosen), but they don't "activate" the selection properly.

### LINKED ISSUE #496: "Hide Empty Sets" in settings sidebar should be "Hide Empty Intersections"
Under the "Filter Intersections" accordion

### PR DESCRIPTION
**Pull request by NateLanza**
### Does this PR close any open issues?
Closes #383 
Closes #458 
Closes #461
Closes #496 

### Give a longer description of what this PR addresses and why it's needed
Simplifies element selection behavior:
- Element selections are no longer bookmarkable. If the chip representing the active element selection is deselected, it remains in the stack & can be reselected (in this case, the selection becomes inactive), but it does not have a bookmark star.
- The element selection chip uses a different icon
- The element selection color is now constant
- Element view only shows items that are currently in intersections in the plot. Practically, this means that if the no-set intersection is hidden, only items from the visible sets are displayed in element view
- Re-labels "Hide Empty Sets" toggle in settings sidebar to the correct "Hide Empty Intersections"
- Re-does ordering of circles in scatterplots such that the current element selection appears on top, then elements in the currently selected intersection, then bookmarked elements, then all others
- Replaces the "X" button for removing plots with a context menu

### Provide pictures/videos of the behavior before and after these changes (optional)
Before:
458-before
After:
better-selection

### Have you added or updated relevant tests?
- [x] Yes
- [ ] No changes are needed

### Have you added or updated relevant documentation?
- [ ] Yes
- [x] No changes are needed

### CODE REVIEW

**Comment by NateLanza** [comment]
Meeting 2/18/25
- Clicking the chip for a current selection should deactivate it but persist the chip

**Comment by JakeWags** [comment]
I don't think this is the intended behavior for this:

upset-selections-bug

If it is, we should talk more about this because I feel like it's pretty jarring! Seems like when I make a selection, it's only actually selecting elements which are bookmarked. If there are no intersection selections/bookmarks, it just filters the selection out.

File: packages/upset/src/atoms/elementsSelectors.ts [hunk 1]
```diff
@@ -14,6 +15,32 @@ import { itemsAtom } from './itemsAtoms';
...
+    return items.filter((item) => {
+      let match = false;
+      visibleSets.forEach((set) => {
+        if (set.startsWith('Set_')) set = set.slice(4);
+        if (item[set]) match = true;
+      });
+      return match;
+    });
+  },
+});
```
Comment (JakeWags) [inline packages/upset/src/atoms/elementsSelectors.ts:43]: Unsure of exactly how `itemsAtom` gets all items, but this should be verified that it works when there is a set query active.

**Review by JakeWags — CHANGES_REQUESTED** [review]
Code looks great. Address behavior issue notes in comments before merge

File: packages/upset/src/atoms/elementsSelectors.ts (hunk 1 above)
Comment (NateLanza) [reply packages/upset/src/atoms/elementsSelectors.ts]: In `Root.tsx` `setItems(data.items)` is called, so it's just all items passed in the `data` arg.

**Review by JakeWags — APPROVED** [review]
Approved 👍
